
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: alamedamachinegroupscalers.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaMachineGroupScaler
    listKind: AlamedaMachineGroupScalerList
    plural: alamedamachinegroupscalers
    singular: alamedamachinegroupscaler
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: AlamedaMachineGroupScaler is the Schema for the alamedamachinegroupscalers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AlamedaMachineGroupScalerSpec defines the desired state of
            AlamedaMachineGroupScaler
          properties:
            machineSets:
              items:
                properties:
                  maxReplicas:
                    format: int32
                    type: integer
                  minReplicas:
                    format: int32
                    type: integer
                  name:
                    type: string
                  namespace:
                    type: string
                  scaleDownDelay:
                    format: int32
                    type: integer
                  scaleUpDelay:
                    format: int32
                    type: integer
                required:
                - name
                - namespace
                type: object
              type: array
            metrics:
              additionalProperties:
                properties:
                  durationDownThresholdPercentage:
                    format: int32
                    type: integer
                  durationUpThresholdPercentage:
                    format: int32
                    type: integer
                  scaleDownGap:
                    format: int32
                    type: integer
                  scaleUpGap:
                    format: int32
                    type: integer
                  utilizationTarget:
                    format: int32
                    type: integer
                type: object
              type: object
          required:
          - machineSets
          - metrics
          type: object
        status:
          description: AlamedaMachineGroupScalerStatus defines the observed state
            of AlamedaMachineGroupScaler
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
